# -*- coding: utf-8 -*-
"""Format_Output_Exercise_LouisKeller

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17N-4ZYRflGMs95zJvsCHqdDDOAINdVCJ
"""

a = "Sum:"
b = "Difference:"
c = "Product:"
d = "Integer Division:"
e = "Average:"
f = "Remainder:"
g = "Exponent:"

integer1 = int(input(""))
integer2 = int(input(""))
sum = integer1 + integer2
Difference = integer1 - integer2
Product = integer1 * integer2
Integer_Division = integer1 / integer2
Average = (integer1 + integer2)/2
Remainder = integer1% integer2
Exponent = integer1**integer2

print()
print(f'{a:<30}', f'{sum:20}')
print(f'{b:<30}', f'{Difference:20}')
print(f'{c:<30}', f'{Product:20}')
print(f'{d:<30}', f'{Integer_Division:20}')
print(f'{e:<30}', f'{Average:20}')
print(f'{f:<30}', f'{Remainder:20}')
print(f'{g:<30}', f'{Exponent:20}')