# -*- coding: utf-8 -*-
"""Lab2LouisKeller

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18hYmNcf1D4heBR1RK8QXos0EMvf9XvG2
"""

from __future__ import barry_as_FLUFL
#Lab2 - Input, Processing, Output
#Louis Keller

#1 : name_printer

print("""+-----------+
|   Louis   |
+-----------+""")

#2 account_balance

initial_account = 1000
earns = 1.5

balance_after_firstyear = initial_account * earns
balance_after_secondyear = balance_after_firstyear * earns
balance_after_thirdyear = balance_after_secondyear * earns

print()
print("The balance after the first year is : ", balance_after_firstyear)
print("The balance after the second year is : ", balance_after_secondyear)
print("The balance after the third year is : ", balance_after_thirdyear)
print()

#3 math_ops

integer1 = int(input("Choose a first integer :"))
integer2 = int(input("Choose a second integer :"))

print()
print("sum : ", integer1+integer2)
print("Difference :", integer1-integer2)
print("Product :", integer1 * integer2)
print("Average :", (integer1+integer2)/2)
print("Distance :", abs(integer1-integer2))
print("Maximum :", max(integer1,integer2))
print("Minimum :", min(integer1,integer2))
print()

#4 f_to_c

f_to_c = int(input("The temperature in Fahrenheit is :"))
print("Now, the temperature in celsius is :", (f_to_c-32)/1.8)
print()

#5 Format_print

num1 = 1.8
num2 = 12.9
num3 = 2
num4 = 100.25
print()
print(f"{num1:.2f}", f"{num2:.2f}", f"{num3:.2f}", f"{num4:.2f}", sep='\n')
print()

#6 print_grid

comb_pattern = "+--+--+--+\n|  |  |  |"
bottom_line = "+--+--+--+"

print()
print(comb_pattern)
print(comb_pattern)
print(comb_pattern)
print(bottom_line)

